import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';
import { Flashcard } from '@/lib/types';

// Render emojis as Twemoji images (default PDF fonts can't draw emoji glyphs)
Font.registerEmojiSource({
  format: 'png',
  url: 'https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/',
});

const styles = StyleSheet.create({
  page: {
    padding: 44,
    fontSize: 10.5,
    fontFamily: 'Helvetica',
    color: '#1f2937',
    lineHeight: 1.55,
  },
  brand: {
    fontSize: 9,
    color: '#6366f1',
    marginBottom: 10,
  },
  h1: {
    fontSize: 18,
    fontFamily: 'Helvetica-Bold',
    color: '#111827',
    marginBottom: 10,
  },
  h2: {
    fontSize: 13,
    fontFamily: 'Helvetica-Bold',
    color: '#4338ca',
    marginTop: 14,
    marginBottom: 6,
    paddingBottom: 3,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  h3: {
    fontSize: 11.5,
    fontFamily: 'Helvetica-Bold',
    color: '#111827',
    marginTop: 8,
    marginBottom: 4,
  },
  paragraph: {
    marginBottom: 6,
  },
  bulletRow: {
    flexDirection: 'row',
    marginBottom: 4,
    paddingLeft: 6,
    paddingRight: 8,
  },
  bulletDot: {
    width: 12,
    color: '#6366f1',
  },
  bulletText: {
    flex: 1,
  },
  bold: {
    fontFamily: 'Helvetica-Bold',
  },
  card: {
    backgroundColor: '#f9fafb',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 4,
    padding: 8,
    marginBottom: 6,
  },
  cardQ: {
    fontFamily: 'Helvetica-Bold',
    marginBottom: 3,
  },
  cardA: {
    color: '#374151',
  },
  source: {
    fontSize: 8.5,
    color: '#9ca3af',
    marginBottom: 14,
  },
  footer: {
    position: 'absolute',
    bottom: 20,
    left: 44,
    right: 44,
    fontSize: 8,
    color: '#9ca3af',
    textAlign: 'center',
  },
});

// Render **bold** spans inside a line
function renderInline(text: string): React.ReactNode[] {
  const parts = text.split(/(\*\*[^*]+\*\*)/g);
  return parts.map((part, i) => {
    if (part.startsWith('**') && part.endsWith('**')) {
      return <Text key={i} style={styles.bold}>{part.slice(2, -2)}</Text>;
    }
    return <Text key={i}>{part}</Text>;
  });
}

// Minimal markdown → react-pdf renderer (headings, bullets, paragraphs)
function renderMarkdown(markdown: string): React.ReactNode[] {
  const lines = markdown.split('\n');
  const nodes: React.ReactNode[] = [];

  lines.forEach((raw, i) => {
    const line = raw.trimEnd();
    const trimmed = line.trim();

    if (!trimmed) return;

    if (trimmed.startsWith('### ')) {
      nodes.push(<Text key={i} style={styles.h3}>{renderInline(trimmed.slice(4))}</Text>);
    } else if (trimmed.startsWith('## ')) {
      nodes.push(<Text key={i} style={styles.h2}>{renderInline(trimmed.slice(3))}</Text>);
    } else if (trimmed.startsWith('# ')) {
      nodes.push(<Text key={i} style={styles.h1}>{renderInline(trimmed.slice(2))}</Text>);
    } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
      nodes.push(
        <View key={i} style={styles.bulletRow} wrap={false}>
          <Text style={styles.bulletDot}>•</Text>
          <Text style={styles.bulletText}>{renderInline(trimmed.slice(2))}</Text>
        </View>
      );
    } else {
      nodes.push(<Text key={i} style={styles.paragraph}>{renderInline(trimmed)}</Text>);
    }
  });

  return nodes;
}

interface NotesPDFProps {
  videoTitle: string;
  youtubeVideoId: string;
  markdown: string;
  flashcards?: Flashcard[];
}

export default function NotesPDF({ videoTitle, youtubeVideoId, markdown, flashcards }: NotesPDFProps) {
  return (
    <Document title={`${videoTitle} — Study Notes`} author="NoteTube AI">
      <Page size="A4" style={styles.page}>
        <Text style={styles.brand}>✨ NoteTube AI — Study Notes</Text>
        <Text style={styles.source}>Source: youtube.com/watch?v={youtubeVideoId}</Text>

        {renderMarkdown(markdown)}

        {flashcards && flashcards.length > 0 ? (
          <>
            <Text style={styles.h2} break>Practice Flashcards</Text>
            {flashcards.map((card, i) => (
              <View key={i} style={styles.card} wrap={false}>
                <Text style={styles.cardQ}>Q{i + 1}. {card.front}</Text>
                <Text style={styles.cardA}>A: {card.back}</Text>
              </View>
            ))}
          </>
        ) : null}

        <Text style={styles.footer} fixed>
          Generated by NoteTube AI · notetubeai.in
        </Text>
      </Page>
    </Document>
  );
}
