"""add_user_notes_to_notes_model

Revision ID: f2ca9f0337cd
Revises: ca4ac16d2c6c
Create Date: 2025-11-28 13:12:56.423714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2ca9f0337cd'
down_revision: Union[str, None] = 'ca4ac16d2c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('user_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('notes', 'notes_model',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'notes_model',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('notes', 'user_notes')
    # ### end Alembic commands ###
